name: Node CI

on: [push,pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
      env:
        CI: true
    - name: Build Client (Prod)
      run:
        npm run build
      env:
        CI: true
    - name: Build Client (Dev)
      run:
        npm run dev
      env:
        CI: true
    - name: Build Client (Test)
      run:
        npm run test-build
      env:
        CI: true
