name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    working-directory: ./desktop
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install & build
      run: |
        npm install
        npm ci
        npm run package
      env:
        CI: true
