name: Node CI

on: [push,pull_request]

jobs:
  lint-js:
    name: Lint Javascript/Typescript via eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
      env:
        CI: true
    - name: Lint
      run: npm run dev:lint
      env:
        CI: true
  lint-py:
    name: Lint via python-black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint (via python-black)
        uses: psf/black@stable
        
